github: [feliciien]  # GitHub Sponsors-enabled username
patreon:  # No Patreon username provided
open_collective:  # No Open Collective username provided
ko_fi:  # No Ko-fi username provided
tidelift:  # No Tidelift platform-name/package-name provided
community_bridge:  # No Community Bridge project-name provided
liberapay:  # No Liberapay username provided
issuehunt:  # No IssueHunt username provided
lfx_crowdfunding:  # No LFX Crowdfunding project-name provided
polar:  # No Polar username provided
buy_me_a_coffee:  # No Buy Me a Coffee username provided
custom:  # No custom sponsorship URLs provided
